# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lofis}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christof Spies", "Moritz Heidkamp"]
  s.date = %q{2010-11-18}
  s.description = %q{Lofis is a small helper to fix lexicographical order for international sorting.}
  s.email = %q{moritz.heidkamp@bevuta.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
    "README.markdown",
    "Rakefile",
    "Rakefile.jeweler",
    "VERSION",
    "lib/lofis.rb",
    "lofis.gemspec",
    "lofis.yml",
    "source/czech_slovak_slovenian.yml",
    "source/french.yml",
    "source/german.yml",
    "source/greek.yml",
    "source/hawaiian.yml",
    "source/italian.yml",
    "source/polish.yml",
    "source/romanian.yml",
    "source/russian.yml",
    "source/spanish.yml",
    "source/turkish.yml"
  ]
  s.homepage = %q{http://github.com/wingfire/lofis}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Lexicographical order for international sorting}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yaml_waml>, [">= 0"])
    else
      s.add_dependency(%q<yaml_waml>, [">= 0"])
    end
  else
    s.add_dependency(%q<yaml_waml>, [">= 0"])
  end
end

